name: Deploy to Server

on:
  push:  # 👈 'push' 이벤트에서 실행되도록 설정
    branches:
      - main  # 👈 'main' 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # 👈 GitHub Actions Runner를 사용하는 경우

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # 👈 저장소 코드 가져오기

      - name: Deploy to Local Server
        run: |
          cd /home/sejong/flask_app/smart_city
          git pull origin main
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart gunicorn_app
